# Generated by Django 4.1.2 on 2022-10-09 19:55

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="AircraftTemplateManager",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "manufacturer",
                    models.CharField(blank=True, max_length=500, null=True),
                ),
                (
                    "aircraft_model",
                    models.CharField(blank=True, max_length=500, null=True),
                ),
                ("icao_code", models.CharField(blank=True, max_length=500, null=True)),
                ("year_manufactured", models.IntegerField(blank=True, null=True)),
                (
                    "aircraft_type",
                    models.CharField(blank=True, max_length=1500, null=True),
                ),
                (
                    "engine_type",
                    models.CharField(blank=True, max_length=500, null=True),
                ),
                (
                    "engine_count",
                    models.CharField(blank=True, max_length=500, null=True),
                ),
                (
                    "manufacturer_serial_no",
                    models.CharField(max_length=500, unique=True),
                ),
                (
                    "manufacturer_line_no",
                    models.CharField(blank=True, max_length=500, null=True),
                ),
                ("registration_no", models.CharField(max_length=500, unique=True)),
                ("iata", models.CharField(max_length=500, unique=True)),
                ("wtc", models.CharField(blank=True, max_length=500, null=True)),
                ("is_active", models.BooleanField(default=True)),
                (
                    "model_3d_image",
                    models.ImageField(
                        blank=True, null=True, upload_to="model_3d_image//%Y/%m/%d"
                    ),
                ),
            ],
            options={
                "ordering": ["-created_at"],
                "permissions": [
                    [
                        "deactivate_aircrafttemplatemanager",
                        "can deactivate aircraft template manager",
                    ],
                    [
                        "print_aircrafttemplatemanager",
                        "can print aircraft template manager",
                    ],
                    [
                        "import_aircrafttemplatemanager",
                        "can import aircraft template manager",
                    ],
                    [
                        "export_aircrafttemplatemanager",
                        "can export aircraft template manager",
                    ],
                ],
            },
        ),
    ]
