# Generated by Django 4.1.2 on 2022-10-25 11:16

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Airline",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("name", models.CharField(max_length=500, unique=True)),
            ],
            options={
                "ordering": ["-created_at"],
                "permissions": [
                    ["deactivate_airline", "can deactivate airline"],
                    ["print_airline", "can print airline"],
                    ["import_airline", "can import airline"],
                    ["export_airline", "can export airline"],
                ],
            },
        ),
        migrations.CreateModel(
            name="Airplane",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("name", models.CharField(max_length=500, unique=True)),
            ],
            options={
                "ordering": ["-created_at"],
                "permissions": [
                    ["deactivate_airplane", "can deactivate airplane"],
                    ["print_airplane", "can print airplane"],
                    ["import_airplane", "can import airplane"],
                    ["export_airplane", "can export airplane"],
                ],
            },
        ),
        migrations.CreateModel(
            name="Airport",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("name", models.CharField(max_length=500, unique=True)),
            ],
            options={
                "ordering": ["-created_at"],
                "permissions": [
                    ["deactivate_airport", "can deactivate airport"],
                    ["print_airport", "can print airport"],
                    ["import_airport", "can import airport"],
                    ["export_airport", "can export airport"],
                ],
            },
        ),
        migrations.CreateModel(
            name="APIProvider",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("name", models.CharField(max_length=500, unique=True)),
                ("endpoint", models.CharField(max_length=1500, unique=True)),
                ("access_key", models.CharField(max_length=1500, unique=True)),
            ],
            options={
                "ordering": ["-created_at"],
                "permissions": [
                    ["deactivate_apiprovider", "can deactivate api provider"],
                    ["print_apiprovider", "can print api provider"],
                    ["import_apiprovider", "can import api provider"],
                    ["export_apiprovider", "can export api provider"],
                ],
            },
        ),
        migrations.CreateModel(
            name="City",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("name", models.CharField(max_length=500, unique=True)),
            ],
            options={
                "ordering": ["-created_at"],
                "permissions": [
                    ["deactivate_city", "can deactivate city"],
                    ["print_city", "can print city"],
                    ["import_city", "can import city"],
                    ["export_city", "can export city"],
                ],
            },
        ),
        migrations.CreateModel(
            name="Country",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("name", models.CharField(max_length=500, unique=True)),
            ],
            options={
                "ordering": ["-created_at"],
                "permissions": [
                    ["deactivate_country", "can deactivate country"],
                    ["print_country", "can print country"],
                    ["import_country", "can import country"],
                    ["export_country", "can export country"],
                ],
            },
        ),
        migrations.CreateModel(
            name="DamageToAirCraft",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("name", models.CharField(max_length=500, unique=True)),
            ],
            options={
                "ordering": ["-created_at"],
                "permissions": [
                    ["deactivate_damagetoaircraft", "can deactivate data settings"],
                    ["print_damagetoaircraft", "can print data settings"],
                    ["import_damagetoaircraft", "can import data settings"],
                    ["export_damagetoaircraft", "can export data settings"],
                ],
            },
        ),
        migrations.CreateModel(
            name="FlightPhase",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "name",
                    models.CharField(
                        choices=[("TAKEOFF", "Takeoff"), ("LANDING", "Landing")],
                        default="PENDING",
                        max_length=500,
                    ),
                ),
            ],
            options={
                "ordering": ["-created_at"],
                "permissions": [
                    ["deactivate_flightphase", "can deactivate flight phase"],
                    ["print_flightphase", "can print flight phase"],
                    ["import_flightphase", "can import flight phase"],
                    ["export_flightphase", "can export flight phase"],
                ],
            },
        ),
        migrations.CreateModel(
            name="HighestInjuryLevel",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("name", models.CharField(max_length=500, unique=True)),
            ],
            options={
                "ordering": ["-created_at"],
                "permissions": [
                    [
                        "deactivate_highestinjurylevel",
                        "can deactivate highest injury level",
                    ],
                    ["print_highestinjurylevel", "can print highest injury level"],
                    ["import_highestinjurylevel", "can import highest injury level"],
                    ["export_highestinjurylevel", "can export highest injury level"],
                ],
            },
        ),
        migrations.CreateModel(
            name="InvestigationStatus",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("name", models.CharField(max_length=500, unique=True)),
            ],
            options={
                "ordering": ["-created_at"],
                "permissions": [
                    [
                        "deactivate_investigationstatus",
                        "can deactivate investigation status",
                    ],
                    ["print_investigationstatus", "can print investigation status"],
                    ["import_investigationstatus", "can import investigation status"],
                    ["export_investigationstatus", "can export investigation status"],
                ],
            },
        ),
        migrations.CreateModel(
            name="Manufacturer",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("name", models.CharField(max_length=500, unique=True)),
            ],
            options={
                "ordering": ["-created_at"],
                "permissions": [
                    ["deactivate_manufacturer", "can deactivate manufacturer"],
                    ["print_manufacturer", "can print manufacturer"],
                    ["import_manufacturer", "can import manufacturer"],
                    ["export_manufacturer", "can export manufacturer"],
                ],
            },
        ),
        migrations.CreateModel(
            name="OccurrenceCategory",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("name", models.CharField(max_length=500, unique=True)),
            ],
            options={
                "ordering": ["-created_at"],
                "permissions": [
                    [
                        "deactivate_occurrencecategory",
                        "can deactivate occurrence category",
                    ],
                    ["print_occurrencecategory", "can print occurrence category"],
                    ["import_occurrencecategory", "can import occurrence category"],
                    ["export_occurrencecategory", "can export occurrence category"],
                ],
            },
        ),
        migrations.CreateModel(
            name="OccurrenceType",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("name", models.CharField(max_length=500, unique=True)),
            ],
            options={
                "ordering": ["-created_at"],
                "permissions": [
                    ["deactivate_occurrencetype", "can deactivate occurrence type"],
                    ["print_occurrencetype", "can print occurrence type"],
                    ["import_occurrencetype", "can import occurrence type"],
                    ["export_occurrencetype", "can export occurrence type"],
                ],
            },
        ),
        migrations.CreateModel(
            name="ReportStatus",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("name", models.CharField(max_length=500, unique=True)),
            ],
            options={
                "ordering": ["-created_at"],
                "permissions": [
                    ["deactivate_reportstatus", "can deactivate report status"],
                    ["print_reportstatus", "can print report status"],
                    ["import_reportstatus", "can import report status"],
                    ["export_reportstatus", "can export report status"],
                ],
            },
        ),
        migrations.CreateModel(
            name="State",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("name", models.CharField(max_length=500, unique=True)),
            ],
            options={
                "ordering": ["-created_at"],
                "permissions": [
                    ["deactivate_state", "can deactivate state"],
                    ["print_state", "can print state"],
                    ["import_state", "can import state"],
                    ["export_state", "can export state"],
                ],
            },
        ),
    ]
