# Generated by Django 4.1.2 on 2022-10-25 11:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("data_settings", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="airline",
            name="country",
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AddField(
            model_name="airline",
            name="hub_code",
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AddField(
            model_name="airline",
            name="iata_code",
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AddField(
            model_name="airline",
            name="icao",
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AddField(
            model_name="airline",
            name="status",
            field=models.BooleanField(default=True, max_length=50),
        ),
        migrations.AddField(
            model_name="airline",
            name="type",
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AddField(
            model_name="airport",
            name="country",
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AddField(
            model_name="airport",
            name="iata_code",
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AddField(
            model_name="airport",
            name="icao",
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AddField(
            model_name="airport",
            name="latitude",
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AddField(
            model_name="airport",
            name="longitude",
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AddField(
            model_name="airport",
            name="timezone",
            field=models.CharField(blank=True, max_length=32),
        ),
        migrations.AddField(
            model_name="city",
            name="iata_code",
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AddField(
            model_name="city",
            name="iso",
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AddField(
            model_name="city",
            name="latitude",
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AddField(
            model_name="city",
            name="longitude",
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AddField(
            model_name="country",
            name="capital",
            field=models.CharField(blank=True, max_length=500),
        ),
        migrations.AddField(
            model_name="country",
            name="fisp_code",
            field=models.CharField(blank=True, max_length=500),
        ),
        migrations.AddField(
            model_name="country",
            name="iso",
            field=models.CharField(blank=True, max_length=500),
        ),
        migrations.AddField(
            model_name="damagetoaircraft",
            name="description",
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name="highestinjurylevel",
            name="description",
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name="investigationstatus",
            name="description",
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name="occurrencecategory",
            name="description",
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name="occurrencetype",
            name="description",
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name="reportstatus",
            name="description",
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name="state",
            name="capital",
            field=models.CharField(blank=True, max_length=500),
        ),
        migrations.AddField(
            model_name="state",
            name="fisp_code",
            field=models.CharField(blank=True, max_length=500),
        ),
        migrations.AddField(
            model_name="state",
            name="iso",
            field=models.CharField(blank=True, max_length=500),
        ),
    ]
