# Generated by Django 4.1.2 on 2022-11-01 08:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        (
            "data_settings",
            "0002_airline_country_airline_hub_code_airline_iata_code_and_more",
        ),
    ]

    operations = [
        migrations.CreateModel(
            name="TypeOfOperation",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("name", models.CharField(max_length=500, unique=True)),
                ("description", models.TextField(blank=True)),
            ],
            options={
                "ordering": ["-created_at"],
                "permissions": [
                    ["deactivate_typeofoperation", "can deactivate type of operation"],
                    ["print_typeofoperation", "can print type of operation"],
                    ["import_typeofoperation", "can import type of operation"],
                    ["export_typeofoperation", "can export type of operation"],
                ],
            },
        ),
    ]
