# Generated by Django 4.1.2 on 2022-11-01 08:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("data_settings", "0003_typeofoperation"),
    ]

    operations = [
        migrations.CreateModel(
            name="AircraftType",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("name", models.CharField(max_length=500, unique=True)),
                ("iata_code", models.CharField(max_length=50)),
            ],
            options={
                "ordering": ["-created_at"],
                "permissions": [
                    ["deactivate_aircrafttype", "can deactivate aircraft type"],
                    ["print_aircrafttype", "can print aircraft type"],
                    ["import_aircrafttype", "can import aircraft type"],
                    ["export_aircrafttype", "can export aircraft type"],
                ],
            },
        ),
    ]
