# Generated by Django 4.1.2 on 2022-11-01 19:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("data_settings", "0004_aircrafttype"),
    ]

    operations = [
        migrations.CreateModel(
            name="Airlab",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("api_key", models.CharField(max_length=1500, unique=True)),
                ("is_active", models.BooleanField(default=True)),
            ],
            options={
                "ordering": ["-created_at"],
                "permissions": [
                    ["deactivate_airlab", "can deactivate airlab"],
                    ["print_airlab", "can print airlab"],
                    ["import_airlab", "can import airlab"],
                    ["export_airlab", "can export airlab"],
                ],
            },
        ),
        migrations.CreateModel(
            name="AviationStack",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("api_key", models.CharField(max_length=1500, unique=True)),
                ("data_offset", models.IntegerField()),
                ("data_per_page", models.IntegerField()),
                ("is_active", models.BooleanField(default=True)),
            ],
            options={
                "ordering": ["-created_at"],
                "permissions": [
                    ["deactivate_aviationstack", "can deactivate aviationstack"],
                    ["print_aviationstack", "can print aviationstack"],
                    ["import_aviationstack", "can import aviationstack"],
                    ["export_aviationstack", "can export aviationstack"],
                ],
            },
        ),
        migrations.AddField(
            model_name="aircrafttype",
            name="is_active",
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name="airline",
            name="is_active",
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name="airplane",
            name="is_active",
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name="airport",
            name="is_active",
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name="apiprovider",
            name="is_active",
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name="city",
            name="is_active",
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name="country",
            name="is_active",
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name="damagetoaircraft",
            name="is_active",
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name="flightphase",
            name="is_active",
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name="highestinjurylevel",
            name="is_active",
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name="investigationstatus",
            name="is_active",
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name="manufacturer",
            name="is_active",
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name="occurrencecategory",
            name="is_active",
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name="occurrencetype",
            name="is_active",
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name="reportstatus",
            name="is_active",
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name="state",
            name="is_active",
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name="typeofoperation",
            name="is_active",
            field=models.BooleanField(default=True),
        ),
    ]
