apiVersion: v1
kind: Service
metadata:
  name: argue-aks-api-service
spec:
  type: LoadBalancer
  selector:
    app: argue-aks-api
  ports:
  - port: 8080
    targetPort: 80


# apiVersion: v1
# kind: Service
# metadata:
#   name: argue-aks-api
# spec:
#   type: LoadBalancer
#   ports:
#   - port: 80
#   selector:
#     app: argue-aks-api
