# Generated by Django 4.1.2 on 2022-10-29 11:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0004_user_change_password_on_first_signin_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="user",
            name="is_verified",
            field=models.BooleanField(default=False),
        ),
    ]
