# Generated by Django 4.1.2 on 2022-10-19 08:38

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="AircraftTemplateManager",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "icao_code",
                    models.CharField(
                        blank=True, max_length=500, null=True, verbose_name="ICAO CODE"
                    ),
                ),
                (
                    "aircraft_model",
                    models.CharField(
                        blank=True,
                        max_length=500,
                        null=True,
                        verbose_name="Aircraft Model",
                    ),
                ),
                (
                    "year_manufactured",
                    models.CharField(
                        blank=True,
                        max_length=500,
                        null=True,
                        verbose_name="Year of manufacture",
                    ),
                ),
                (
                    "model_3d_image",
                    models.ImageField(
                        blank=True,
                        null=True,
                        upload_to="model_3d_image//%Y/%m/%d",
                        verbose_name="Aircraft Image",
                    ),
                ),
                (
                    "type",
                    models.CharField(
                        blank=True,
                        max_length=1500,
                        null=True,
                        verbose_name="Aircraft Type",
                    ),
                ),
                (
                    "description",
                    models.CharField(
                        blank=True,
                        max_length=500,
                        null=True,
                        verbose_name="Description",
                    ),
                ),
                (
                    "engine_type",
                    models.CharField(
                        blank=True,
                        max_length=500,
                        null=True,
                        verbose_name="Engine Type",
                    ),
                ),
                (
                    "engine_count",
                    models.CharField(
                        blank=True,
                        max_length=500,
                        null=True,
                        verbose_name="Engine Count",
                    ),
                ),
                (
                    "wtc",
                    models.CharField(
                        blank=True,
                        max_length=500,
                        null=True,
                        verbose_name="Wake Turbulence Category",
                    ),
                ),
                (
                    "iata",
                    models.CharField(
                        blank=True, max_length=500, null=True, verbose_name="IATA Code"
                    ),
                ),
                (
                    "data_source",
                    models.CharField(
                        default="DIRECT", max_length=500, verbose_name="Source of data"
                    ),
                ),
                (
                    "is_active",
                    models.BooleanField(default=True, verbose_name="Active Status"),
                ),
            ],
            options={
                "ordering": ["-created_at"],
                "permissions": [
                    [
                        "deactivate_aircrafttemplatemanager",
                        "can deactivate aircraft template manager",
                    ],
                    [
                        "print_aircrafttemplatemanager",
                        "can print aircraft template manager",
                    ],
                    [
                        "import_aircrafttemplatemanager",
                        "can import aircraft template manager",
                    ],
                    [
                        "export_aircrafttemplatemanager",
                        "can export aircraft template manager",
                    ],
                ],
            },
        ),
        migrations.CreateModel(
            name="Manufacturer",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("name", models.CharField(max_length=200, unique=True)),
            ],
            options={
                "ordering": ["-created_at"],
                "permissions": [
                    ["deactivate_manufacturer", "can deactivate aircraft manufacturer"],
                    ["print_manufacturer", "can print aircraft manufacturer"],
                    ["import_manufacturer", "can import aircraft manufacturer"],
                    ["export_manufacturer", "can export aircraft manufacturer"],
                ],
            },
        ),
    ]
