# Generated by Django 4.1.2 on 2022-10-25 11:16

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="OccurrenceMetaData",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("title", models.CharField(max_length=200, unique=True)),
                ("report_number", models.CharField(blank=True, max_length=200)),
                ("location", models.CharField(blank=True, max_length=200)),
                ("departure", models.CharField(blank=True, max_length=200)),
                ("destination", models.CharField(blank=True, max_length=200)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("ACTIVE", "Active"),
                            ("COMPLETED", "Completed"),
                            ("DISCONTINUED", "Discontinued"),
                            ("DEACTIVATED", "Deactivated"),
                        ],
                        default="ACTIVE",
                        max_length=200,
                    ),
                ),
                ("is_active", models.BooleanField(default=True)),
                (
                    "published_status",
                    models.CharField(
                        choices=[
                            ("PENDING", "Pending"),
                            ("INTERIM", "Interim"),
                            ("PRELIMINARY", "Preliminary"),
                            ("FINAL", "Final"),
                        ],
                        default="PENDING",
                        max_length=200,
                    ),
                ),
            ],
            options={
                "ordering": ["-created_at"],
                "permissions": [
                    [
                        "deactivate_occurrencemetadata",
                        "can deactivate occurrence meta data",
                    ],
                    ["print_occurrencemetadata", "can print occurrence meta data"],
                    ["import_occurrencemetadata", "can import occurrence meta data"],
                    ["export_occurrencemetadata", "can export occurrence meta data"],
                ],
            },
        ),
        migrations.CreateModel(
            name="ReportSection",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("title", models.CharField(max_length=200, unique=True)),
                ("is_active", models.BooleanField(default=True)),
                ("published_status", models.BooleanField(default=False)),
                (
                    "occurrence_report",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="occurrence_report.occurrencemetadata",
                    ),
                ),
            ],
            options={
                "ordering": ["-created_at"],
                "permissions": [
                    ["deactivate_reportsection", "can deactivate report section"],
                    ["print_reportsection", "can print report section"],
                    ["import_reportsection", "can import report section"],
                    ["export_reportsection", "can export report section"],
                ],
            },
        ),
        migrations.CreateModel(
            name="ReportSubSection",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("title", models.CharField(max_length=200, unique=True)),
                ("is_active", models.BooleanField(default=True)),
                ("published_status", models.BooleanField(default=False)),
                (
                    "report_section",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="occurrence_report.reportsection",
                    ),
                ),
            ],
            options={
                "ordering": ["-created_at"],
                "permissions": [
                    [
                        "deactivate_reportsubsection",
                        "can deactivate report sub section",
                    ],
                    ["print_reportsubsection", "can print report sub section"],
                    ["import_reportsubsection", "can import report sub section"],
                    ["export_reportsubsection", "can export report sub section"],
                ],
            },
        ),
    ]
